#!/bin/bash
#
# Update remote git(hub) repository with lacells-creator results
#
# Make sure you've sourced `config` and `util` and run `config_default`
# when using this as a library.
#
# Licensed under GPLv3 or later
# (c)2015 wvengen & n76

dogit() {
  pushd "$LACELLS_GIT_DIR"
  git $@
  popd
}

splitcsv() {
  rm -f $1_*
  split -a1 -C50MB "$1.csv" "$1_"
  rm -f "$1.csv"
  for i in $1_*; do mv "$i" "$i.csv"; done
}

addfilescsv() {
  # Add a rightmost files column to the countries csv
  cd "$1"
  awk -v PREFIX="$3" -F , \
    '{ gsub(/\s*$/, ""); if($1!="mcc") { printf("%s,", $0); system("echo `ls " PREFIX $1"*.csv`"); } else { print $0 ",urls"; }}' \
    <"$2" >"$2.new" &&
      mv "$2.new" "$2"
  cd - >/dev/null
}

checkgit() {
  # Make sure we have an up-to-date git repository
  if [ ! -d "$LACELLS_GIT_DIR/.git" ]; then
    echo "Please initialize a git repository in $LACELLS_GIT_DIR with a default remote" 1>&2
    exit 1
  fi
}

prepare() {
  # Update data files
  rm -f "$LACELLS_GIT_DIR/lacells-*"
  cp "$LACELLS_DIR"/lacells-* "$LACELLS_GIT_DIR/"

  # Github doesn't like big files, split them.
  # TODO use find-command instead of harded list here
  splitcsv "$LACELLS_GIT_DIR/lacells-mcc_208"
  splitcsv "$LACELLS_GIT_DIR/lacells-mcc_234"
  splitcsv "$LACELLS_GIT_DIR/lacells-mcc_250"
  splitcsv "$LACELLS_GIT_DIR/lacells-mcc_262"
  splitcsv "$LACELLS_GIT_DIR/lacells-mcc_310"
  splitcsv "$LACELLS_GIT_DIR/lacells-mcc_404"
  splitcsv "$LACELLS_GIT_DIR/lacells-mcc_440"
  splitcsv "$LACELLS_GIT_DIR/lacells-mcc_724"

  # Add filenames to lacells-countries.csv
  addfilescsv "$LACELLS_GIT_DIR" "lacells-countries.csv" "lacells-mcc_"

  # Add website files
  cp "$PREFIX"/misc/html/* "$LACELLS_GIT_DIR/"
}

# Commit and push changes
upload() {
  dogit add -A && \
  dogit commit -m lacells-update && \
  dogit push -f -q $GIT_PUSH_ARGS 2>&1 | grep -v 'remote: warning: \(GH001\|See\|.*this is larger than\)' 1>&2
}

# Remove lines <2 points, because we need to stay <1GB
reduce() {
  for i in $LACELLS_GIT_DIR/*.csv; do
    cat "$i" | grep -v ',1$' >"$i.new" && mv "$i.new" "$i"
  done
}

# Main program
if [ `basename $0` = upload-git ]; then
  # expects to be run as misc/upload-git
  PREFIX="`dirname $0`/.."
  source "$PREFIX/lib/config"
  source "$PREFIX/lib/util"
  config_default "$PREFIX"
  config_from_options $@
  prepare
  #reduce
  upload
fi
